# SwiftLint Configuration for SwiftSamsungFrame
# Swift 6 with strict concurrency enabled

# Opt-in rules
opt_in_rules:
  - explicit_type_interface
  - explicit_acl
  - closure_spacing
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments during development
  - line_length # Let formatter handle this

# Rule configurations
type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - up
    - to
    - tv
    - ws
    - ip

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Packages

# Swift 6 Concurrency
# These are enforced by compiler with StrictConcurrency feature
# SwiftLint should not conflict with compiler checks
