# SwiftLint Configuration for Swift 6 Samsung TV Client
# Enforces Swift 6 concurrency rules and project conventions

excluded:
  - .build
  - .swiftpm
  - Tests/LinuxMain.swift
  - Tests/**/XCTestManifests.swift

opt_in_rules:
  - explicit_acl
  - explicit_top_level_acl
  - explicit_enum_raw_value
  - explicit_type_interface
  - function_default_parameter_at_end
  - prefer_self_in_static_references
  - redundant_type_annotation
  - strict_fileprivate
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

disabled_rules:
  - todo
  - line_length

# Concurrency and Sendable enforcement
force_cast: error
force_try: error
force_unwrapping: warning
implicit_return: error
large_tuple: warning

# Line Length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Function Length
function_body_length:
  warning: 60
  error: 100

# Type Length
type_body_length:
  warning: 300
  error: 400

# File Length
file_length:
  warning: 500
  error: 800

# Identifier Names
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL

# Nesting
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

reporter: "xcode"
